### ISSUE TITLE
Cannot start Lxqt session

### ISSUE THREAD

**Issue by VoidCnTL** [stefonarch/lxqt-labwc-session#7] opened 2024-03-11 15:34 UTC
I am using Arch Linux with the testing repo enabled. I installed lxqt-labwc-session with Aur. When attempting to start from SDDM or even directly through the startlxqtlabwc command, it fails.

My recent [logs](https://paste.rs/HDGmm.txt).

Please let me know if any other information required.

P.S. The regular X11 Lxqt seems to launch just fine with other WMs like Kwin, etc.

**Comment by stefonarch** [comment] 2024-03-11 15:55
It looks like the issue is labwc e/o the config file.
`Mar 11 20:55:14 archer kernel: labwc[12430]: segfault at 80 ip 000074cba73b35a4 sp 00007fffc8a02e18 error 4 in libxkbcommon.so.0.0.0[74cba7399000+1f000] likely on CPU 5 (core 6, socket 0)`

Try just from inside LXQt x11 or any other system:
`labwc -C /tmp -s qterminal` it should open a nested session. If that works the issue is in the configuration.

`labwc -v` is?

**Comment by VoidCnTL** [comment] 2024-03-11 16:00
The `labwc -C /tmp -s qterminal` works and it launches a nested session. `labwc -v` is `0.7.1`

**Comment by stefonarch** [comment] 2024-03-11 16:52
Looking closer at the log the error seems to be about the keymap. What  is  in
`cat ~/.config/lxqt-wayland/labwc/environment` ?

**Comment by VoidCnTL** [comment] 2024-03-11 17:57
```# LXQt labwc environment file

# This allows xdg-desktop-portal-wlr to function (e.g. for screen-recording)
# XDG_CURRENT_DESKTOP=wlroots

# Disable hardware cursors. Most users wouldn't want to do this, but if you
# are experiencing issues with disappearing cursors, this might fix it.
#WLR_NO_HARDWARE_CURSORS=1

# For Java applications such as JetBrains/Intellij Idea, set this variable
# to avoid menus with incorrect offset and blank windows
# See https://github.com/swaywm/sway/issues/595
_JAVA_AWT_WM_NONREPARENTING=1

# Firefox
MOZ_ENABLE_WAYLAND=1

# Cursor theme and size are imported from LXQt at login. Configure under LXQt in "Appearance → Cursor".
# Keyboard layout and toggle options are imported only once from LXQt, edit here to change
XKB_DEFAULT_LAYOUT=en
XCURSOR_SIZE=
XCURSOR_THEME=```

**Comment by stefonarch** [comment] 2024-03-11 18:26
```
XCURSOR_THEME=```
``` 
at the end is probably from formatting here I think?

I'm not sure but labwc does not yet allow empty variables. Check
```
 cat ~/.config/lxqt/session.conf |grep -i cur

```
 and fill in the values in the environment file.

**Comment by tsujan** [comment] 2024-03-11 18:39
labwc's crash log shows `xkb_state_get_keymap`. Something wants to get keymap with X11?

**Comment by VoidCnTL** [comment] 2024-03-11 18:39
Yea that was from the formatting. I tried doing the `cat ~/.config/lxqt/session.conf` and the only thing I got is 
```
[General]
__userfile__=true
window_manager=kwin_x11
```

**Comment by stefonarch** [comment] 2024-03-11 18:46
Ok, that's probably where the settingsimporter failed, there is a fallback using "$LANG" but not for empty cursor. Log into LXQt x11 and configure cursor theme and size, remove the empty vars in labwc environment file and try again.

@tsujan xkb is used also under wayland, my env:

```
XKB_DEFAULT_LAYOUT=it,ch
XKB_DEFAULT_OPTIONS=grp:caps_toggle,grp_led:scroll
XCURSOR_SIZE=32
XCURSOR_THEME=Bibata-Original-Classic
```

**Comment by stefonarch** [comment] 2024-03-11 18:50
Ok, that's probably where the settingsimporter failed, there is a fallback using "$LANG" but not for empty cursor. Log into LXQt x11 and configure cursor theme and size, remove the empty vars in labwc environment file and try again.

@tsujan xkb is used also under wayland, my env:

```
XKB_DEFAULT_LAYOUT=it,ch
XKB_DEFAULT_OPTIONS=grp:caps_toggle,grp_led:scroll
XCURSOR_SIZE=32
XCURSOR_THEME=Bibata-Original-Classic
```

**Comment by stefonarch** [comment] 2024-03-11 18:51
It has to be something else. I tested with empty vars and it doesn't fail here.

**Comment by stefonarch** [comment] 2024-03-11 19:01
Do you have something x11-only in `~/.config/autostart` ?

**Comment by VoidCnTL** [comment] 2024-03-11 19:06
So I commented out the lines relating to Xcursor and I am able to get into the session but it definitely feels weird. When it started I was able to see two panels one of which was right in the middle of my screen (and the desktop definitely didn't feel like labwc) when I pressed exit it somehow brought me to the 'real' bare-bones labwc desktop.

Anyways, [logs](https://paste.rs/ZN4qI.txt) for the session here. Still needs some more tinkering but at least I am able to start the session now. 

Screenshot here:
![20240312_00h40m27s_grim](https://github.com/stefonarch/lxqt-labwc-session/assets/90516471/03a19abd-7ea1-4e82-a7f9-836d2eb55b19)

With that said, I'll check back in tomorrow but thanks for the help in getting this running.

Btw is it intended that there is no option to configure Display/Monitors through the Lxqt Monitor Settings app yet?

**Comment by stefonarch** [comment] 2024-03-11 19:44
Ok, nice. Read the [notes](https://github.com/stefonarch/lxqt-labwc-session#notes) please. In session settings you need to disable/stop "panel" and enable only "Panel x11/wayland".

When LXQt 2 is released things will be different, this session has it's limits.
For displays you need `wdisplays`, LXQt's tool is not ready.
 More useful apps are listed [here](https://github.com/stefonarch/LXQt-Wayland-files#3rd-party-tools).

**Comment by johanmalm** [comment] 2024-03-11 19:45
I think `XKB_DEFAULT_LAYOUT=en` is incorrect. For English, use 'us' or 'gb'.
I'll do a patch to handle failure to create keymap (as a result of bad `XKB_DEFAULT_LAYOUT`) in a more sensible way.

**Comment by stefonarch** [comment] 2024-03-11 19:48
O thanks, that's the reason. This is the fallback from the script which uses `$LANG` when nothing is configured. Will try to fix it.

**Comment by stefonarch** [comment] 2024-03-11 20:10
Should be fixed on my side now by 561689a4c940d984a0fca6e6a03c26598398bbd2

**Closed as completed by stefonarch** 2024-03-11 20:10 UTC

**Comment by Consolatis** [comment] 2024-03-11 22:32
> I'm not sure but labwc does not yet allow empty variables.

Just for completeness: labwc will currently just ignore empty variables (e.g. doesn't change them at all). In the next release labwc should then set them as empty.

**Comment by stefonarch** [comment] 2024-03-12 12:50
@VoidCnTL looking at the screenshot... You could install pcmanfm-qt with full wayland support. Just modify the PKGBUILD:
`source=("git+https://github.com/lxqt/$_pkgname.git#branch=shell_qt")`

Then you can remove all window rules for pcmanfm-qt in `~/.config/lxqt-wayland/labwc/rc.xml` .

**Comment by VoidCnTL** [comment] 2024-03-12 13:58
@stefonarch I tried but there are build errors from Lxqt-build-tools version numbering with the git packages seeking the git version of the lxqt-build-tools but it errors out while actually building pcmanfm/libfm. It is a whole nesting issue that is leading me to believe in either manually editing each PKGBUILD (to edit out lxqt-build-tool) or installing directly through source. So I will wait for things to settle down on that front before trying it out, but thanks for pinging me. I'll keep an eye out for it.
